name: Test
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out your repository using git
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
        
      - name: Build the project
        run: yarn build

      - name: Install dependencies
        run: yarn install

      - name: Run Jest
        run: yarn test